services:
  # Frontend
  - type: web
    name: vitalogistica-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://vitalogistica-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Backend
  - type: web
    name: vitalogistica-backend
    env: node
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 